#!/bin/sh
# Autolaunch supervisor for the custom rtos_core/mujina stack (Linux
# side). Runs under rcS, which uses a real busybox ash shell -- while
# loops work here, unlike RT-Smart's msh (see main.c's --ipc6loop
# comment for why the RTOS side has to loop internally in C instead).
#
# rtos_core.elf itself is launched separately by /sharefs/init.sh on
# the RTOS/big-core side (--ipc6loop, loops forever internally). This
# script only supervises the Linux-side processes.
APP=/mntapp/release/linux/app

# Each supervised process gets its own restart loop, backgrounded
# independently so one crashing doesn't affect the others. A short
# delay between restarts avoids spinning hot if something is
# persistently broken (no network, pool down, etc).
#
# No MUJINA_LOG override: the built-in default (warn,mujina_miner=info)
# is quiet enough for normal operation. Binary lives in /data (not
# /mntapp -- that partition is only 7.4MB total, far too small for this
# static binary).

# nano3s_ui FIRST (2026-09-12): it is the process that reads fb_page
# and draws, so it must be running before the boot-logo page below is
# written. The old order wrote the page while nothing was rendering --
# the panel just kept whatever the stock splash left and the logo
# never appeared.
(
    while true; do
        /data/nano3s_ui > /sharefs/nano3s_ui.log 2>&1
        sleep 3
    done
) &

# fb_button, ble_setup and the harness all come up while the logo is on
# screen. ble_setup (first-boot WiFi provisioning: BLE GATT server the
# Avalon Family app talks to, service 0xFFFF, protocol compatible with
# nano3ble) advertising from the earliest moment is exactly what we
# want -- the app finds the device right away. It exits by itself once
# wlan0 has an address (checked internally, 60s idle cycle), so this
# loop costs nothing after WiFi is configured -- and is what makes the
# device discoverable when it has no credentials yet. Without this loop
# the binary just sits unused on /data and the device is invisible to
# the app.
(
    while true; do
        $APP/fb_button > /sharefs/fb_button.log 2>&1
        sleep 3
    done
) &

(
    while true; do
        # hciconfig hci0 down first (mirrors the proven alpha-v2 loop):
        # ble_setup claims HCI_CHANNEL_USER, which needs hci0 clean and
        # unmanaged -- a previous instance that exited while holding it
        # (or anything that left it up) makes the next HCI bind fail and
        # the device silently never advertises again.
        hciconfig hci0 down 2>/dev/null
        /data/ble_setup > /sharefs/ble_setup.log 2>&1
        sleep 3
    done
) &

# Power/fan idle-control harness (2026-07-29) -- no IPC of its own, just
# power_en (GPIO34) + fan (pwm4) sysfs control driven by pause/resume
# requests via /tmp/harness_control. See mujina_test_harness.c.
(
    while true; do
        $APP/mujina_test_harness > /sharefs/harness.log 2>&1
        sleep 3
    done
) &

# Boot logo: with the renderer now running, put the panel on the
# "bootlogo" page so the owner's logo (bootlogo.rgb565, generated by
# tools/make_bootlogo.py and shipped at /mntapp/release/linux/app/) is
# the first thing on screen after the stock splash. nano3s_ui's first
# poll sees the page and blits the raw image; 8s later the live UI page
# takes over. The page file does the holding, not this sleep -- if the
# UI is ever slow to init and misses the bootlogo window it simply
# starts on the live page (the logo is a nicety, never worth blocking
# boot over; the UI also skips the page if the file is absent).
echo bootlogo > $APP/fb_page
sleep 8

echo nano3s > $APP/fb_page

# Wait for wlan0 to have an address before starting the miner -- up to
# 60s, matching this project's other network-dependent bringup scripts.
# Deliberately between the logo hold and mujina-minerd: without it the
# supervisor would retry the miner every 3s and spam its info log while
# the network is still coming up.
i=0
while [ $i -lt 60 ]; do
    ip=$(ifconfig wlan0 2>/dev/null | grep 'inet addr:' | cut -d: -f2 | cut -d' ' -f1)
    if [ -n "$ip" ]; then
        break
    fi
    i=$((i + 1))
    sleep 1
done

(
    while true; do
        MUJINA_NANO3S_ENABLE=1 MUJINA_NANO3S_POWER_TARGET_W=62.0 MUJINA_API_LISTEN=0.0.0.0:80 MUJINA_POOL_URL=stratum+tcp://pool.256foundation.org:3333 MUJINA_POOL_USER=YOUR_WALLET.YOUR_WORKER /data/mujina-minerd > /data/mujina-minerd.log 2>&1
        sleep 3
    done
) &

# Log size watchdog: mujina-minerd.log has no built-in rotation, so even
# at the quiet default level it grows without bound over a long-running
# session. Checked every 5 minutes; if it exceeds 5MB, kill the process
# (not truncate the file directly -- externally truncating a file a
# process is actively writing to via a fixed fd offset can desync the
# write position and produce a sparse file that jumps right back up,
# same class of bug found in rtos_core's ipc6.log fix). The supervisor
# loop above already restarts mujina-minerd on exit and reopens its log
# with plain shell '>' redirection, which truncates cleanly on process
# start -- so killing it here is what actually resets the file safely.
(
    while true; do
        sleep 300
        if [ -f /data/mujina-minerd.log ]; then
            SIZE=$(wc -c < /data/mujina-minerd.log)
            if [ "$SIZE" -gt 5242880 ]; then
                PID=$(pidof mujina-minerd)
                if [ -n "$PID" ]; then
                    kill "$PID"
                fi
            fi
        fi
    done
) &
